CREATE OR REPLACE VIEW dep10_only AS
SELECT * FROM employees
WHERE dept_id = 10
WITH CHECK OPTION;

BEGIN 
    INSERT INTO dept10_only VALUES(4,'Kiran',10,42000);
    INSERT INTO dep10_only VALUES(5,'Vivek',20,48000);
EXCEPTION
    WHEN OTHER THEN
        DBMS_OUTPUT.PUT_LINE('Error: '||SQLERRM);
END;
/
